"""empty message

Revision ID: 375067b84dfe
Revises: 
Create Date: 2021-07-15 18:25:45.761630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375067b84dfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sneakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sneakers')
    # ### end Alembic commands ###
