"""empty message

Revision ID: fab223bc7d2b
Revises: 12521cbb8a09
Create Date: 2021-07-23 15:27:01.775766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab223bc7d2b'
down_revision = '12521cbb8a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sneakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('colorway', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('retail_price', sa.BigInteger(), nullable=True),
    sa.Column('estimated_market_value', sa.BigInteger(), nullable=True),
    sa.Column('story', sa.String(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('id_in_source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original', sa.String(), nullable=True),
    sa.Column('small', sa.String(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('sneaker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sneaker_id'], ['sneakers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stockx', sa.String(), nullable=True),
    sa.Column('goat', sa.String(), nullable=True),
    sa.Column('flight_club', sa.String(), nullable=True),
    sa.Column('sneaker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sneaker_id'], ['sneakers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    op.drop_table('images')
    op.drop_table('sneakers')
    op.drop_table('sources')
    # ### end Alembic commands ###
